<?php include __DIR__ . '/../partials/_property_photos_1.phtml'; ?>

<div class="text">
	<?php include __DIR__ . '/../partials/_property_details.phtml'; ?>

	<?php include __DIR__ . '/../partials/_property_description.phtml'; ?>

	<?php include __DIR__ . '/../partials/_property_controls.phtml'; ?>
</div>

<div class="clear"></div>

<?php include __DIR__ . '/../partials/_property_location.phtml'; ?>
