<div class="details">
	<?php

	if ($house['division'] == 'bog')
	{
		parariusoffice_grouped_details($house, get_option('nomis_property_bog_details'));
	}
	elseif (get_option('nomis_property_different_sale_details') == '1' && $house['forsale'] == '1')
	{
		parariusoffice_grouped_details($house, get_option('nomis_property_sale_details'));
	}
	else
	{
		parariusoffice_details($house, get_option('nomis_property_details'));
	}

	?>
	<div class="clear"></div>
</div>
